name: Build and Deploy PWA Docker Image

on:
  push:
    branches: [ bootstrap ]
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '(pwa):') && !contains(github.event.head_commit.message, '!skip-ci')"
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 Running on branch ${{ github.ref }} with commit ${{ github.sha }} in ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npx nx test pwa
    - run: npx nx build pwa 
    - run: npx nx server pwa
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        file: ./pwa.Dockerfile
        push: true
        tags: |
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/mbat-pwa:${{ github.sha }}

    - name: CapRover App Deploy
      uses: floms/action-caprover@v1
      with:
        host: '${{ secrets.CAPROVER_DOMAIN }}'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        app: '${{ secrets.CAPROVER_PWA_APP_NAME }}'
        image: "ghcr.io/${{ secrets.DOCKER_USERNAME }}/mbat-pwa:${{ github.sha }}"
